SELECT * FROM EMPLOYEE ORDER BY SALARY DESC;
CREATE SEQUENCE SEQ_EID;
UPDATE EMPLOYEE SET ENT_DATE=SYSDATE, ENT_YN='Y' WHERE EMP_ID=221;
ROLLBACK;
SELECT * FROM (SELECT * FROM EMPLOYEE ORDER BY SALARY DESC) WHERE ROWNUM<=5 ;

SELECT * FROM EMPLOYEE WHERE BONUS IS NOT NULL;
SELECT * FROM EMPLOYEE WHERE DEPT_CODE IS NULL;
SELECT * FROM EMPLOYEE ORDER BY EMP_NAME;
